use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :ammotion, AmmoWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
                    cd: Path.expand("../assets", __DIR__)]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ammotion, AmmoWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/ammotion_web/views/.*(ex)$},
      ~r{lib/ammotion_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :ammotion, Ammo.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "ammotion_dev",
  hostname: "localhost",
  pool_size: 10,
  extensions: [{Geo.PostGIS.Extension, library: Geo}]

System.put_env("FACEBOOK_APP_ID", "")
System.put_env("FACEBOOK_APP_SECRET", "")
System.put_env("FACEBOOK_REDIRECT_URI", "")

System.put_env("GITHUB_CLIENT_ID", "29657aa9dbca3da3b415")
System.put_env("GITHUB_CLIENT_SECRET", "9fb016b9055d18d3fe308585666e43e2a9ac3a39")

System.put_env("GOOGLE_CLIENT_ID", "")
System.put_env("GOOGLE_CLIENT_SECRET", "")
System.put_env("GOOGLE_REDIRECT_URI", "")

System.put_env("SLACK_CLIENT_ID", "")
System.put_env("SLACK_CLIENT_SECRET", "")

System.put_env("TWITTER_CONSUMER_KEY", "")
System.put_env("TWITTER_CONSUMER_SECRET", "")
